const str = "JavaScript is simple but not easy to master";
const wordLimit = 3;

// my solution
function truncateWithWordLimit(str, wordLimit) {
  // write your solution here
  return str.split(" ").splice(0, wordLimit).join(" ");
}

//truncateStringtoWordLimit
//this is generated by github copilot
function truncateStringtoWordLimit(str, wordLimit) {
  let result = "";
  let words = str.split(" ");
  if (words.length <= wordLimit) {
    return str;
  }
  for (let i = 0; i < wordLimit; i++) {
    result += words[i] + " ";
  }
  return result.trim() + "...";
}

console.log(`Truncated string: ${truncateWithWordLimit(str, wordLimit)}`);
